apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-helloworld
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-helloworld
  template:
    metadata:
      labels:
        app: helm-helloworld
    spec:
      containers:
        - name: helm-helloworld-container
          image: "asia-northeast3-docker.pkg.dev/test-project-11542/cicd/dockerfile:v2"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
