#test1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-helloworld
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hello-world.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-world.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "asia-northeast3-docker.pkg.dev/test-project-11542/cicd/dockerfile:v5"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name : http
            containerPort: 80
            protocol: TCP
