apiVersion: v1
kind: Service
metadata:
  name: {{ include ".Values.nameOverride" . }}
  labels:
    {{- include ".Values.nameOverride.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    {{- include ".Values.nameOverride.selectorLabels" . | nindent 4 }}
