#1

replicaCount: 2

image:
  repository: asia-northeast3-docker.pkg.dev/test-project-11542/cicd/dockerfile:v1
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  
printValues: "hello world2!"
nameOverride: "helm-helloworld"

frontendConfig:
  enabled: false
  name: ""
  sslPolicy: ""

backendConfig:
  enabled: false
  name: ""
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 3
    requestPath: /

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80
    
ingress:
  enabled: true
  className: ""
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.global-static-ip-name: gke-static-ip
  path: /
  hosts:
  - host: 172.16.0.2

service:
  type: ClusterIP
  port: 8080
