name: Deploy
#1
on:
  pull_request:
    branches: [ "main" ]

env:
  CHART_PATH: helm-helloworld/
  RELEASE_NAME: helm-helloworld
  NAMESPACE: default

jobs:
  prepare:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
                    
      - name: Helm tool installer
        uses: Azure/setup-helm@v3

      - name: Print the Helm client version information
        run: helm version
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/461568029406/locations/global/workloadIdentityPools/github-cicd-pool/providers/cicd-provider
          service_account: 'wif-test@test-project-11542.iam.gserviceaccount.com'
          audience: 'https://github.com/minkyu0425/cicd-cd'

      - name: Examine the chart for possible issues          
        run: helm lint ${{ env.CHART_PATH }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

      - name: Use gcloud CLI
        run: gcloud info
        
      - name: Install Google Cloud Auth plugin
        run: gcloud components install gke-gcloud-auth-plugin
      
      - name: Get Kubernetes config
        run: gcloud container clusters get-credentials cicd-cluster --region asia-northeast3 --project test-project-11542
      
      - name: Dry-run the release
        run: |
          helm upgrade ${{ env.RELEASE_NAME }} ${{ env.CHART_PATH }} \
             --namespace ${{ env.NAMESPACE }} \
             --install \
             --dry-run

  deploy:
    needs: prepare
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
                    
      - name: Helm tool installer
        uses: Azure/setup-helm@v3 

      - name: Print the Helm client version information
        run: helm version

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/461568029406/locations/global/workloadIdentityPools/github-cicd-pool/providers/cicd-provider
          service_account: 'wif-test@test-project-11542.iam.gserviceaccount.com'
          audience: 'https://github.com/minkyu0425/cicd-cd'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

      - name: Install Google Cloud Auth plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Get Kubernetes config
        run: gcloud container clusters get-credentials cicd-cluster --region asia-northeast3 --project test-project-11542
        
      - name: Examine the chart for possible issues          
        run: helm lint ${{ env.CHART_PATH }}

      - name: Upgrade the release
        run: |
          helm upgrade ${{ env.RELEASE_NAME }} ${{ env.CHART_PATH }} \
          --namespace ${{ env.NAMESPACE }} \
          --install 

      - name: List the upgrade result
        run: helm list --filter ${{ env.RELEASE_NAME }} --namespace ${{ env.NAMESPACE }}
